[package]
    name = "pan_bindings"
    version = "1.0.0"
    edition = "2021"


[build-dependencies]
bindgen = "0.65.1"
tokio = { version = "1.0", features = ["full"] }
log = "0.4.20"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
bindgen = "0.65.1"
log = "0.4.20"

